"""Add expected reporting date

Revision ID: 4586c849120f
Revises: 8de1ab3414af
Create Date: 2021-10-18 19:44:47.813301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586c849120f'
down_revision = '8de1ab3414af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('expected_reporting_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'expected_reporting_date')
    # ### end Alembic commands ###
