"""Add resolved_value column

Revision ID: 4c2be755eff7
Revises: 599c122f2c73
Create Date: 2021-10-06 18:14:54.387954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2be755eff7'
down_revision = '599c122f2c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('resolved_value', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'resolved_value')
    # ### end Alembic commands ###
