"""Add in Request Access Model

Revision ID: 7dada3c9676d
Revises: 8ab5c8a42848
Create Date: 2021-08-30 13:01:16.769427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dada3c9676d'
down_revision = '8ab5c8a42848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('company', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_access')
    # ### end Alembic commands ###
