"""empty message

Revision ID: 8ab5c8a42848
Revises: 
Create Date: 2021-08-28 21:23:11.719286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab5c8a42848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('fiscal_period', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('value_string', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('beat_address', sa.String(), nullable=True),
    sa.Column('beat_price', sa.Numeric(), nullable=True),
    sa.Column('miss_address', sa.String(), nullable=True),
    sa.Column('miss_price', sa.Numeric(), nullable=True),
    sa.Column('issued', sa.Integer(), nullable=True),
    sa.Column('highlight_market', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    # ### end Alembic commands ###
