"""empty message

Revision ID: 9baea9dac1a5
Revises: c864421f8ab1
Create Date: 2022-01-04 18:23:37.351499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baea9dac1a5'
down_revision = 'c864421f8ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notifications_portfolio_events', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('notifications_market_events', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications_market_events')
    op.drop_column('user', 'notifications_portfolio_events')
    # ### end Alembic commands ###
