"""empty message

Revision ID: c864421f8ab1
Revises: 1d7f92b5108f
Create Date: 2021-12-22 16:56:18.913612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c864421f8ab1'
down_revision = '1d7f92b5108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matic_faucet_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('error_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('matic_recieved', sa.Numeric(), nullable=True))
    op.add_column('user', sa.Column('matic_recieved_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'matic_recieved_date')
    op.drop_column('user', 'matic_recieved')
    op.drop_column('user', 'address')
    op.drop_table('matic_faucet_queue')
    # ### end Alembic commands ###
